name: firmware_updater
description: Firmware Updater
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^2.1.1
  fwupd: #^0.1.0
    git:
      url: https://github.com/robert-ancell/fwupd.dart.git
      ref: unix-fd

  provider: ^5.0.0
  yaru: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
