name: firmware-updater
version: git
summary: Firmware Updater
description: Update Firmware
confinement: strict
base: core22
grade: devel
license: GPL-3.0+
icon: snap/local/firmware-updater.png
architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  dbus:
    interface: dbus
    name: com.canonical.firmware_updater
    bus: session

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $CRAFT_PART_INSTALL/usr/bin/dart
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  firmware-updater:
    after: [ flutter-git ]
    plugin: nil
    source: .
    override-build: |
      set -eux
      flutter channel stable
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      dart pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

  firmware-notifier:
    after: [ flutter-git, firmware-updater ]
    plugin: nil
    source: ./packages/firmware_notifier/
    override-build: |
      set -eux
      dart pub get
      mkdir -p $CRAFT_PART_INSTALL/bin/
      dart compile exe bin/firmware_notifier.dart -o $CRAFT_PART_INSTALL/bin/firmware-notifier

apps:
  firmware-updater:
    command: bin/firmware-updater
    desktop: bin/data/flutter_assets/assets/firmware-updater.desktop
    extensions: [gnome]
    plugs:
      - fwupd
      - upower-observe

  firmware-notifier:
    command: bin/firmware-notifier
    extensions: [gnome]
    plugs:
      - desktop
      - fwupd
      - upower-observe
