name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: sudo apt update
    - run: sudo apt install -y lcov
      env:
        DEBIAN_FRONTEND: noninteractive
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  run:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter test

  integration:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: sudo apt update
    - run: sudo apt install -y clang cmake curl dbus dbus-x11 fwupd fwupd-tests gsettings-desktop-schemas libgtk-3-dev ninja-build pkg-config unzip upower xvfb
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Prepare environment
      run: |
        sudo sed -i 's/DisabledPlugins=.*/DisabledPlugins=invalid;bios/g' /etc/fwupd/daemon.conf
        echo "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$UID/bus" >> $GITHUB_ENV
        echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
        gsettings set org.gnome.desktop.interface gtk-theme 'Yaru'
    - run: sudo fwupdmgr enable-remote fwupd-tests
    - run: sudo fwupdmgr get-devices
    - run: sudo -E xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' $FLUTTER_ROOT/bin/flutter test integration_test
